# Generated by Django 5.0.6 on 2024-07-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_borrow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='book_returned',
            field=models.BooleanField(default=False),
        ),
    ]
