# Generated by Django 5.0.6 on 2024-07-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_borrow_book_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_price',
            field=models.IntegerField(),
        ),
    ]
